/**
 * Scanner Screen — Real QR Code scanning via expo-camera.
 * Parses the lecturer's JSON QR payload, validates expiry,
 * then navigates to GPS verification with the parsed data.
 */
import React, { useState, useRef, useCallback } from 'react';
import {
  View,
  Text,
  StyleSheet,
  SafeAreaView,
  StatusBar,
} from 'react-native';
import { useRouter } from 'expo-router';
import { CameraView, useCameraPermissions, BarcodeScanningResult } from 'expo-camera';
import { FontAwesome } from '@expo/vector-icons';
import { useTheme } from '@/hooks/useTheme';
import { Spacing, Typography } from '@/constants/Layout';
import { PrimaryButton, SecondaryButton } from '@/components/ui';
import { api, ApiError } from '@/lib/api';

/** Shape of the QR payload generated by the lecturer web app */
interface QRPayload {
  token: string;
  courseId: string;
  courseCode: string;
  lat: number | null;
  lng: number | null;
  lecturerAccuracy: number | null;
  radius: number;
  exp: number;
}

export default function ScannerScreen() {
  const router = useRouter();
  const theme = useTheme();
  const [permission, requestPermission] = useCameraPermissions();
  const [scanned, setScanned] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const processingRef = useRef(false);

  const handleBarCodeScanned = useCallback(
    (result: BarcodeScanningResult) => {
      // Prevent double-processing
      if (processingRef.current) return;
      processingRef.current = true;
      setScanned(true);

      (async () => {
        try {
          const payload: QRPayload = JSON.parse(result.data);

          // Validate required fields
          if (!payload.token || !payload.courseCode || !payload.exp) {
            throw new Error('Invalid QR code — missing required fields');
          }

          // Validate token format (starts with SA-)
          if (!payload.token.startsWith('SA-')) {
            throw new Error('This QR code is not from Smart Attendance');
          }

          // Check expiry
          if (Date.now() > payload.exp) {
            setError('This QR code has expired. Ask your lecturer to refresh it.');
            return;
          }

          // Check if already attended this session
          try {
            const check = await api.checkAttendance(payload.courseId);
            if (check.alreadyMarked) {
              setError('You have already marked attendance for this session.');
              return;
            }
          } catch {
            // If check fails (network etc.), continue — the server will still reject duplicates
          }

          // Success — navigate to GPS verify with all QR data
          router.replace({
            pathname: '/gps-verify',
            params: {
              token: payload.token,
              courseId: payload.courseId,
              courseCode: payload.courseCode,
              lat: payload.lat?.toString() ?? '',
              lng: payload.lng?.toString() ?? '',
              lecturerAccuracy: payload.lecturerAccuracy?.toString() ?? '',
              radius: payload.radius.toString(),
              exp: payload.exp.toString(),
            },
          });
        } catch (e: any) {
          if (!error) {
            setError(e.message || 'Could not read QR code. Make sure you scan the attendance QR.');
          }
        }
      })();
    },
    [router, error],
  );

  const handleRetry = () => {
    setScanned(false);
    setError(null);
    processingRef.current = false;
  };

  // ── Permission not yet determined ──
  if (!permission) {
    return (
      <SafeAreaView style={[styles.container, { backgroundColor: '#000' }]}>
        <StatusBar barStyle="light-content" />
        <View style={styles.centered}>
          <Text style={styles.permissionText}>Requesting camera permission...</Text>
        </View>
      </SafeAreaView>
    );
  }

  // ── Permission denied ──
  if (!permission.granted) {
    return (
      <SafeAreaView style={[styles.container, { backgroundColor: '#000' }]}>
        <StatusBar barStyle="light-content" />
        <View style={styles.centered}>
          <FontAwesome name="camera" size={64} color="#666" />
          <Text style={[styles.permissionText, { marginTop: Spacing.lg }]}>
            Camera access is required to scan QR codes
          </Text>
          <PrimaryButton
            title="Grant Permission"
            icon="unlock"
            onPress={requestPermission}
            style={{ marginTop: Spacing.lg, minWidth: 200 }}
          />
          <SecondaryButton
            title="Go Back"
            onPress={() => router.back()}
            style={{ marginTop: Spacing.md, borderColor: '#555' }}
          />
        </View>
      </SafeAreaView>
    );
  }

  // ── Error state ──
  if (error) {
    return (
      <SafeAreaView style={[styles.container, { backgroundColor: '#000' }]}>
        <StatusBar barStyle="light-content" />
        <View style={styles.header}>
          <SecondaryButton
            title="Cancel"
            onPress={() => router.back()}
            style={{ borderColor: '#fff', paddingHorizontal: 16 }}
          />
          <Text style={styles.headerTitle}>Scan QR Code</Text>
          <View style={{ width: 80 }} />
        </View>
        <View style={styles.centered}>
          <FontAwesome name="exclamation-triangle" size={64} color="#F87171" />
          <Text style={[styles.permissionText, { color: '#F87171', marginTop: Spacing.lg }]}>
            {error}
          </Text>
          <PrimaryButton
            title="Try Again"
            icon="refresh"
            onPress={handleRetry}
            style={{ marginTop: Spacing.lg, minWidth: 200 }}
          />
        </View>
      </SafeAreaView>
    );
  }

  // ── Camera scanning ──
  return (
    <SafeAreaView style={[styles.container, { backgroundColor: '#000' }]}>
      <StatusBar barStyle="light-content" />

      {/* Header */}
      <View style={styles.header}>
        <SecondaryButton
          title="Cancel"
          onPress={() => router.back()}
          style={{ borderColor: '#fff', paddingHorizontal: 16 }}
        />
        <Text style={styles.headerTitle}>Scan QR Code</Text>
        <View style={{ width: 80 }} />
      </View>

      {/* Camera Preview */}
      <View style={styles.cameraContainer}>
        <CameraView
          style={StyleSheet.absoluteFill}
          facing="back"
          barcodeScannerSettings={{ barcodeTypes: ['qr'] }}
          onBarcodeScanned={scanned ? undefined : handleBarCodeScanned}
        />

        {/* Overlay with scan frame */}
        <View style={styles.overlay}>
          <View style={styles.overlayTop} />
          <View style={styles.overlayMiddle}>
            <View style={styles.overlaySide} />
            <View style={styles.scanFrame}>
              {/* Corner markers */}
              <View style={[styles.corner, styles.topLeft]} />
              <View style={[styles.corner, styles.topRight]} />
              <View style={[styles.corner, styles.bottomLeft]} />
              <View style={[styles.corner, styles.bottomRight]} />
            </View>
            <View style={styles.overlaySide} />
          </View>
          <View style={styles.overlayBottom} />
        </View>
      </View>

      {/* Status */}
      <View style={styles.statusArea}>
        {scanned ? (
          <>
            <FontAwesome name="check-circle" size={24} color="#4ADE80" />
            <Text style={[styles.statusText, { color: '#4ADE80' }]}>
              QR Code Scanned — Verifying GPS Location...
            </Text>
          </>
        ) : (
          <>
            <FontAwesome name="qrcode" size={24} color="#fff" />
            <Text style={styles.statusText}>
              Point your camera at the QR code displayed by your lecturer
            </Text>
          </>
        )}
      </View>

      {/* Bottom Info */}
      <View style={styles.bottomInfo}>
        <View style={styles.infoRow}>
          <FontAwesome name="map-marker" size={16} color={theme.primary} />
          <Text style={styles.infoText}>
            GPS location will be verified after scanning
          </Text>
        </View>
        <View style={styles.infoRow}>
          <FontAwesome name="lock" size={16} color={theme.primary} />
          <Text style={styles.infoText}>
            QR codes expire every 30 seconds
          </Text>
        </View>
      </View>
    </SafeAreaView>
  );
}

const FRAME_SIZE = 260;
const OVERLAY_COLOR = 'rgba(0,0,0,0.6)';

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  centered: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: Spacing.xl,
  },
  permissionText: {
    ...Typography.body,
    color: '#ccc',
    textAlign: 'center',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.md,
    zIndex: 10,
  },
  headerTitle: {
    ...Typography.h3,
    color: '#fff',
  },
  cameraContainer: {
    flex: 1,
    position: 'relative',
  },
  // ── Overlay (darkens everything except the scan frame) ──
  overlay: {
    ...StyleSheet.absoluteFillObject,
  },
  overlayTop: {
    flex: 1,
    backgroundColor: OVERLAY_COLOR,
  },
  overlayMiddle: {
    flexDirection: 'row',
    height: FRAME_SIZE,
  },
  overlaySide: {
    flex: 1,
    backgroundColor: OVERLAY_COLOR,
  },
  overlayBottom: {
    flex: 1,
    backgroundColor: OVERLAY_COLOR,
  },
  scanFrame: {
    width: FRAME_SIZE,
    height: FRAME_SIZE,
  },
  corner: {
    position: 'absolute',
    width: 40,
    height: 40,
    borderColor: '#1565C0',
    borderWidth: 3,
  },
  topLeft: {
    top: 0,
    left: 0,
    borderRightWidth: 0,
    borderBottomWidth: 0,
    borderTopLeftRadius: 12,
  },
  topRight: {
    top: 0,
    right: 0,
    borderLeftWidth: 0,
    borderBottomWidth: 0,
    borderTopRightRadius: 12,
  },
  bottomLeft: {
    bottom: 0,
    left: 0,
    borderRightWidth: 0,
    borderTopWidth: 0,
    borderBottomLeftRadius: 12,
  },
  bottomRight: {
    bottom: 0,
    right: 0,
    borderLeftWidth: 0,
    borderTopWidth: 0,
    borderBottomRightRadius: 12,
  },
  statusArea: {
    alignItems: 'center',
    paddingHorizontal: Spacing.xl,
    paddingVertical: Spacing.lg,
    gap: Spacing.sm,
  },
  statusText: {
    ...Typography.body,
    color: '#fff',
    textAlign: 'center',
  },
  bottomInfo: {
    paddingHorizontal: Spacing.xl,
    paddingBottom: Spacing.xxl,
    gap: Spacing.sm,
  },
  infoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
  },
  infoText: {
    ...Typography.bodySmall,
    color: 'rgba(255,255,255,0.7)',
  },
});
